### PR TITLE
Fixing steemRSS

### PR DESCRIPTION
**Pull request by itamarbareket**
I've removed the junk, these are the distilled changes 

I would recommend though to update `.gitignore` so anything under `lib` won't be pushed in 😄

### CODE REVIEW

**Comment by imkimchi** [comment]
when I run this update, I get `_steem2.default.api.setOptions is not a function`.

what does the function actually do? I didn't use steem library for a while, I have no idea what it does.

**Comment by imkimchi** [comment]
updated steem to 0.6.7 now it's working. thanks :)

**Comment by itamarbareket** [comment]
You have to change the default steem node as steemd node retired on January 6th. This method enables you to change the steem node URL. It's required until they fix it.
Though it's `steem.api.setOptions()` see https://github.com/steemit/steem-js/issues/284#issuecomment-346936218

**Comment by itamarbareket** [comment]
Oh Okay, no worries :)

**Comment by imkimchi** [comment]
off topic, but how did you find this repo? I didn't contain the project since june lol

**Comment by itamarbareket** [comment]
A friend was relying on Streemian's RSS feeds in order to automate her blog posts, and it's down now. So she wanted help searching for alternatives. Ended up fixing this repo and deploying it to heroku

**Comment by imkimchi** [comment]
Steemian's RSS feed has so many unsupported features and really uncomfortable to use, that's why I made this, I hope you find this project helpful :) thank you for the PR again!

**Comment by imkimchi** [comment]
@doriitamar I just found out the app was not running on the server, I fixed everything and It's working well in https://steemrss.com again 😄

**Comment by itamarbareket** [comment]
Great! Thank you

**Comment by imkimchi** [comment]
@doriitamar I ran the server with pm2 so It won't be never down like before 😆

**Pull request merged**
